extends SceneTree
func _initialize() -> void:
 var store:=EditionStore.new()
 var path:="/tmp/mafa-character-restore-"+Crypto.new().generate_random_bytes(8).hex_encode()+".sqlite";store.path=path;assert(store.open())
 var accounts:=EditionAccounts.new();accounts.store=store
 accounts.data={"version":1,"accounts":[{"id":"f".repeat(32),"username":"fixture","salt":"0".repeat(32),"hash":"0".repeat(64),"iterations":LocalAccounts.ITERATIONS,"characters":[]}]};accounts.current_id="f".repeat(32)
 var c:=accounts.create_character("恢复角色","战士","女",false,"classic");assert(not c.is_empty())
 var rules:=EditionRules.new();rules.store=store;assert(rules.attach(c))
 var world:=store.load_world(c.id)
 var before:=accounts.data.duplicate(true)
 assert(not accounts.archive_character(c.id,"错误名称") and accounts.data==before)
 assert(store.db.query("PRAGMA query_only=ON;"))
 assert(not accounts.archive_character(c.id,c.name) and accounts.data==before)
 assert(store.db.query("PRAGMA query_only=OFF;"))
 assert(accounts.archive_character(c.id,c.name));assert(accounts.character(c.id).is_empty())
 before=accounts.data.duplicate(true)
 assert(store.db.query("PRAGMA query_only=ON;"))
 assert(not accounts.restore_character(c.id) and accounts.data==before)
 assert(store.db.query("PRAGMA query_only=OFF;"))
 assert(accounts.restore_character(c.id));assert(accounts.character(c.id)==c and store.load_world(c.id)==world)
 assert(not accounts.restore_character(c.id))
 assert(accounts.load_database());accounts.current_id="f".repeat(32)
 var restored:=accounts.character(c.id)
 assert(restored==JSON.parse_string(JSON.stringify(c)) and accounts.characters().size()==1)
 assert(accounts.archive_character(c.id,c.name))
 var duplicate:=accounts.create_character(c.name,"法师","男")
 assert(not duplicate.is_empty());before=accounts.data.duplicate(true)
 assert(not accounts.restore_character(c.id) and accounts.data==before and accounts.message.contains("同名"))
 assert(accounts.archive_character(duplicate.id,duplicate.name))
 for name in ["角色甲","角色乙","角色丙"]:assert(not accounts.create_character(name,"战士","男").is_empty())
 before=accounts.data.duplicate(true)
 assert(not accounts.restore_character(c.id) and accounts.data==before and accounts.message.contains("槽位"))
 var slot: Dictionary=accounts.characters()[0]
 assert(accounts.archive_character(slot.id,slot.name));assert(accounts.restore_character(c.id))
 assert(accounts.characters().size()==3 and accounts.character(c.id)==restored and store.load_world(c.id)==world)
 var corrupt:=accounts.data.duplicate(true)
 corrupt.accounts[0].archived.append({"id":"missing-fields"})
 assert(not accounts.valid_db(corrupt))
 corrupt=accounts.data.duplicate(true);corrupt.accounts[0].archived.append(accounts.character(c.id).duplicate(true))
 assert(not accounts.valid_db(corrupt))
 assert(accounts.valid_db(accounts.data))
 var encoded: String=JSON.stringify(corrupt)
 assert(store.put_metadata("accounts",encoded))
 assert(not accounts.load_database() and not accounts.healthy and accounts.current_id.is_empty())
 assert(not accounts.persist({"version":1,"accounts":[]}))
 assert(store.read_metadata("accounts")==encoded and store.load_world(c.id)==world)
 print("PASS: malformed account load blocks subsequent writes and preserves database content")
 print("PASS: malformed archived records and duplicate active/archive identities are rejected")
 print("PASS: name conflict and full slots preserve archive; freeing a slot restores original world")
 print("PASS: archive/restore write failures preserve identity; retry and reload preserve character and world without duplicates")
 store.close()
 for suffix in ["","-wal","-shm",".backup.sqlite"]:DirAccess.remove_absolute(path+suffix)
 quit()
