extends SceneTree
func _initialize() -> void:
 var store:=EditionStore.new();store.path="/tmp/mafa-shop-death-"+Crypto.new().generate_random_bytes(8).hex_encode()+".sqlite"
 assert(store.open())
 var rules:=EditionRules.new();rules.store=store
 assert(rules.attach({"id":"shop-death","name":"交易检查","job":"战士","gender":"女"}))
 rules.state.hp=0
 var before: Dictionary=rules.state.duplicate(true)
 for buying in [true,false]:
  assert(not rules.shop("potion",1,buying))
  assert(rules.message=="死亡期间不能买卖物品" and rules.state==before)
  assert(not rules.reference_trade("server:merchant:56","potion",buying,0))
  assert(rules.message=="死亡期间不能买卖物品" and rules.state==before)
 for depositing in [true,false]:
  assert(not rules.warehouse("potion",depositing))
  assert(rules.message=="死亡期间不能存取物品" and rules.state==before)
 assert(not rules.repair() and rules.state==before)
 assert(not rules.reference_repair("server:merchant:56") and rules.state==before)
 rules.state.hp=130
 assert(rules.shop("potion",1,false))
 assert(rules.state.inventory.potion==before.inventory.potion-1)
 assert(rules.warehouse("potion",true))
 assert(rules.warehouse("potion",false))
 assert(rules.state.inventory.potion==before.inventory.potion-1)
 assert(rules.repair())
 var damaged: Dictionary=rules.state.duplicate(true)
 damaged.items=damaged.items.filter(func(item):return item.container!="equipment")
 var weapon:=EditionInventory.make_item("wood_sword",1,"equipment",0,60)
 damaged.items.append(weapon);damaged.gold=39;EditionInventory.mirror(damaged)
 assert(rules.apply(damaged,"damaged_repair_fixture"))
 var unrepaired: Dictionary=rules.state.duplicate(true)
 assert(not rules.repair() and rules.state==unrepaired)
 damaged=rules.state.duplicate(true);damaged.gold=100
 assert(rules.apply(damaged,"repair_balance_fixture"))
 unrepaired=rules.state.duplicate(true)
 assert(store.db.query("PRAGMA query_only=ON;"))
 assert(not rules.repair() and rules.state==unrepaired)
 assert(store.db.query("PRAGMA query_only=OFF;"))
 assert(rules.repair())
 assert(rules.state.gold==60 and EditionInventory.find_item(rules.state,weapon.uid).durability==100)
 assert(rules.repair() and rules.state.gold==60)
 damaged=rules.state.duplicate(true)
 EditionInventory.find_item(damaged,weapon.uid).durability=60
 var armor:=EditionInventory.make_item("ref:5",1,"equipment",1,50)
 var spare:=EditionInventory.make_item("wood_sword",1,"inventory",EditionInventory.free_slot(damaged.items,"inventory"),20)
 damaged.items.append(armor);damaged.items.append(spare);damaged.gold=1000;EditionInventory.mirror(damaged)
 assert(rules.apply(damaged,"category_repair_fixture"))
 var quote: Dictionary=rules.reference_repair_quote("server:merchant:56")
 assert(quote.items.size()==1 and quote.items[0].uid==weapon.uid and quote.cost>0)
 assert(rules.reference_repair("server:merchant:56"))
 assert(rules.state.gold==1000-int(quote.cost))
 assert(EditionInventory.find_item(rules.state,weapon.uid).durability==100)
 assert(EditionInventory.find_item(rules.state,armor.uid).durability==50)
 assert(EditionInventory.find_item(rules.state,spare.uid).durability==20)
 var repaired: Dictionary=rules.state.duplicate(true)
 assert(not rules.reference_repair("server:merchant:56") and rules.state==repaired)
 var stocked: Dictionary=rules.state.duplicate(true)
 var other:=EditionInventory.make_item("wood_sword",1,"inventory",EditionInventory.free_slot(stocked.items,"inventory"),90)
 stocked.items.append(other);EditionInventory.mirror(stocked);assert(rules.apply(stocked,"same_name_sale_fixture"))
 var sale_before: Dictionary=rules.state.duplicate(true)
 assert(store.db.query("PRAGMA query_only=ON;"))
 assert(not rules.reference_trade("server:merchant:56","wood_sword",false,0,spare.uid))
 assert(rules.state==sale_before)
 assert(store.db.query("PRAGMA query_only=OFF;"))
 assert(rules.reference_trade("server:merchant:56","wood_sword",false,0,spare.uid))
 assert(EditionInventory.find_item(rules.state,spare.uid).is_empty())
 assert(EditionInventory.find_item(rules.state,other.uid).durability==90)
 assert(EditionInventory.find_item(rules.state,weapon.uid).container=="equipment")
 var after_sale: Dictionary=rules.state.duplicate(true)
 assert(not rules.reference_trade("server:merchant:56","wood_sword",false,0,spare.uid))
 assert(rules.state==after_sale)
 var limited: Dictionary=rules.state.duplicate(true)
 limited.gold=10000
 limited.merchant_stock={"server:merchant:56:wood_sword":{"count":1,"at":0}}
 assert(rules.apply(limited,"limited_stock_fixture"))
 var stock_before: Dictionary=rules.state.duplicate(true)
 assert(store.db.query("PRAGMA query_only=ON;"))
 assert(not rules.reference_trade("server:merchant:56","wood_sword",true,0))
 assert(rules.state==stock_before)
 assert(store.db.query("PRAGMA query_only=OFF;"))
 assert(rules.reference_trade("server:merchant:56","wood_sword",true,0))
 assert(rules.state.merchant_stock["server:merchant:56:wood_sword"].count==0)
 assert(rules.state.inventory.wood_sword==stock_before.inventory.wood_sword+1)
 var sold_out: Dictionary=rules.state.duplicate(true)
 assert(not rules.reference_trade("server:merchant:56","wood_sword",true,59))
 assert(rules.state==sold_out and rules.message=="该商品暂时售罄")
 assert(rules.reference_trade("server:merchant:56","wood_sword",true,60))
 assert(rules.state.merchant_stock["server:merchant:56:wood_sword"].count==49)
 var full: Dictionary=rules.state.duplicate(true)
 full.items=full.items.filter(func(item):return item.container!="inventory")
 for index in range(48):full.items.append(EditionInventory.make_item("wood_sword",1,"inventory",index))
 full.level=100;full.gold=10000;EditionInventory.mirror(full)
 assert(rules.apply(full,"full_bag_purchase_fixture"))
 var full_before: Dictionary=rules.state.duplicate(true)
 assert(not rules.reference_trade("server:merchant:56","wood_sword",true,61))
 assert(rules.state==full_before and rules.message=="背包或仓库没有空格")
 var release_uid: String=rules.state.items.filter(func(item):return item.container=="inventory")[0].uid
 assert(rules.inventory_action("move",{"uid":release_uid,"container":"warehouse","slot":0}))
 var remaining: int=rules.state.merchant_stock["server:merchant:56:wood_sword"].count
 assert(rules.reference_trade("server:merchant:56","wood_sword",true,61))
 assert(rules.state.merchant_stock["server:merchant:56:wood_sword"].count==remaining-1)
 assert(rules.state.items.filter(func(item):return item.container=="inventory").size()==48)
 var heavy: Dictionary=rules.state.duplicate(true)
 heavy.items=heavy.items.filter(func(item):return item.container!="inventory")
 heavy.level=1
 var unit_weight: int=EditionRules.ITEMS.potion.weight
 heavy.items.append(EditionInventory.make_item("potion",int(105/unit_weight),"inventory",0))
 EditionInventory.mirror(heavy);assert(rules.apply(heavy,"weight_limit_fixture"))
 var heavy_before: Dictionary=rules.state.duplicate(true)
 assert(not rules.reference_trade("server:merchant:56","wood_sword",true,61))
 assert(rules.state==heavy_before and rules.message=="背包负重不足")
 print("PASS: dead buy/sell rejected by both shop rules without mutation; alive sale, warehouse roundtrip and repair succeed; dead warehouse/repair rejected; damaged repair cost, insufficient funds, failed save retry verified; NPC repair respects category and equipped status; exact-instance sale rollback/retry and stale UID rejection; stock rollback, sold-out rejection and timed restock; full inventory preserves state and retry fills freed slot; weight and capacity errors distinguished")
 var path:=store.path;store.close()
 for suffix in ["","-wal","-shm",".backup.sqlite"]:DirAccess.remove_absolute(path+suffix)
 quit()
